### ISSUE TITLE
Feature Request: Multi Allocation

### ISSUE THREAD

**Issue by Aaranaw** [learnweb/moodle-mod_ratingallocate#174] opened 2019-05-20 08:41 UTC
Hi, we are interested in using Rating Allocate to distribute voluntary markers for students.
Currently, the plugin will only assign a user a single time, would it be possible to set the number of times a user can be allocated and not restrict it to a single choice?

**Comment by tobiasreischmann** [comment] 2019-05-24 12:54
Hey,
this is a duplicate of #17. It is currently not in our backlog to extend the plugin, since it is algorithmically not very easy.

**Closed by tobiasreischmann** 2019-05-24 12:54 UTC
